import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./src/components/layout/Navbar";
import Footer from "./src/components/layout/Footer/Footer";
import MotionSection from "./src/components/effects/MotionSection";
import FallingApricot from "./src/components/effects/FallingApricot";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={`${roboto.className} antialiased`}>
        <img src="/logo_zalo.svg" alt="logoZalo" className="fixed z-50 right-2 bottom-30" />
        <img
          src="/vikki-hotline-icon.png"
          alt="vikki-hotline-icon"
          className="fixed right-2 bottom-0 z-50  "
        />
        <FallingApricot />
        <Navbar />
        {children}
        <MotionSection delay={0}>
          <Footer />
        </MotionSection>
      </body>
    </html>
  );
}
